{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  stripPrefix:
    prefixes:
      {{- range .Values.ingress.hosts }}
      {{- range .paths }}
      - {{ .path }}
      {{- end }}
      {{- end }}
{{- end }}